### ISSUE TITLE
Automate generation of list and string types

### ISSUE THREAD

**Issue by torfmaster** [torfmaster/hackdose-sml-parser#2]
Currently list and string types are generated by running the tests in `parser.rs` and copying the output to the grammar. However, there are probably smarter ways of implementing this, for example

* use a build script to generate the grammar
* find a way of implementing types generic over integers in the `peg`-crate

I am happy to tutor this issue so don't hesitate to try!

**Comment by paulzzy** [comment]
Hi! I'd be willing to help out with this issue. Heads up that I have minimal Rust experience, so I will be asking a lot of questions if that's okay with you.

**Comment by torfmaster** [comment]
Hi @paulzzy, thank you for volunteering! I'm happy to assist you with this issue. A first shot could be the following:

You could use [build scripts](https://doc.rust-lang.org/cargo/reference/build-scripts.html) to generate the grammar in `src/parser.rs`. The grammar is mostly static the sml list bodies and string function can be generated. A template how to generate those can actually be found in the tests of the parser (e.g. `generate_strings()`.
Now you can go ahead and let me know in case you have questions. Have fun!

**Comment by paulzzy** [comment]
Thanks for accepting me! Would the build script generate `src/parser.rs` directly or is there some way for the file to read the output of the build script?

**Comment by torfmaster** [comment]
Tbh I had to look this up as well: You can output the file to `OUT_DIR` as specified [here](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts).

Btw: You can consider using a procedural macro as well, if you feel more comfortable with that - however no guarantee that this will work :)

**Comment by paulzzy** [comment]
Hello! Apologies for the long wait—had finals and other schoolwork the past couple weeks.

Anyways, I think I found a solution: `peg` repeat ranges can be specified with a [Rust expression](https://docs.rs/peg/latest/peg/#repeat-ranges). This avoids using a build script or procedural macros, neither of which are easy to maintain (or easy for me to learn lol).

For example, the [`list_sml_value()` rule](https://github.com/torfmaster/hackdose-sml-parser/blob/690b8d2bf930ceda66615d1cf13239426399701d/src/parser.rs#L89) is currently defined as `list_sml_value1()/list_sml_value2()/...`. It can be concisely rewritten as
```rust
rule list_sml_value() -> Vec<SmlListEntry> =
    prefix: [0x71..=0x7f]
    value: single_sml_value() * <{
        let length = prefix - 0x70;
        length as usize
    }>
    { value }
```

Also, for the `string()` rule I'm not quite sure what the correct grammar is. Currently [`string16()`](https://github.com/torfmaster/hackdose-sml-parser/blob/690b8d2bf930ceda66615d1cf13239426399701d/src/parser.rs#L217) is
```rust
rule string16() -> Vec<u8> = [0x11] n:(any_number())*<16,16> { n }
```
But in the output of `cargo test -- --nocapture`, `string16()` is
```rust
rule string16() -> Vec<u8> = [0x81] [0x02] n:(any_number())*<16,16> { n }
```

Looks like [`generate_strings()`](https://github.com/torfmaster/hackdose-sml-parser/blob/690b8d2bf930ceda66615d1cf13239426399701d/src/parser.rs#L404-L424) uses ranges that don't match the grammar code. What's the correct grammar here?

**Comment by torfmaster** [comment]
Hi, thank you for digging into the topic! I was completely unaware that you can bind the prefix, what a great finding! 

```rust
rule string16() -> Vec<u8> = [0x11] n:(any_number())*<16,16> { n }
```
is plain wrong, the second option is correct.
As you can see in the `generate_strings()` function there are two (completely different) ways how strings are represented. I guess you would have to write two separate rules for them.

**Comment by torfmaster** [comment]
Hi, @paulzzy.  FYI: I merged the hackdose into the hackdose monorepo and I am happy to receive your PR there :) See https://github.com/torfmaster/hackdose
