### ISSUE TITLE
Add more obis codes

### ISSUE THREAD

**Issue by torfmaster** [torfmaster/hackdose-sml-parser#3]
The obis codes [here](https://www.promotic.eu/en/pmdoc/Subsystems/Comm/PmDrivers/IEC62056_OBIS.htm) are used to identify values from smart meters inside the library. While there is automation (a macro) in place to generate necessary code from a relatively simple format, only few codes have been added.

In order to save manual labour the table from the link can be brought into the desired format using a relatively simple search-and-replace operation using regexes (or just multicursor action). The relevant source file is `obis.rs`.

I am happy to tutor this issue so don't hesitate to try!

**Comment by Angr1st** [comment]
I want to try adding all the other OBIS codes mentioned in the table on the page you linked. 
The OBIS Code is shown to be displayed in this format "A-B:C.D.E*F".  In the OBIS codes you already added, you've set A to 1, B to 0 and F to 255. The table only seems to show the values for C, D and E. Should I assume the same values for A, B and F? Where would I find the complete table with A, B and F?

**Comment by torfmaster** [comment]
Hi! Thank you for you interest in the project. I would for now only consider the registers linked to electricity. You can use A=1 (designating electricity) B=0 (designating "default channel") and F=255 (I actually didn't find the meaning). In the future when we find use case where the values A,B, F are interesting we can make the solution more flexible, but for now this should be okay.

I have thought about extracting the info using a regexp on the HTML code of the linked page + conversion of text to PascalCase but that might be overkill.

If you have further questions, feel free to ask, otherwise happy coding :)

**Comment by Angr1st** [comment]
> I would for now only consider the registers linked to electricity

That means I should not add the OBIS Codes from 11. - 13. as they are more general?

**Comment by torfmaster** [comment]
Sounds reasonable for me :)

**Comment by torfmaster** [comment]
Fixed by #4

**Comment by Angr1st** [comment]
Don't you mean #4, instead of #1? Your Issue #1 seems still open to me.

torfmaster ***@***.***> schrieb am Sa., 3. Dez. 2022, 10:44:
